# Generated by Django 5.2 on 2025-04-25 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='default_files', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pptx', 'PPTX'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], default='pptx', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
