# Generated by Django 5.2 on 2025-04-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_filename_remove_file_user_file_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('can_download_file', 'Can download file')]},
        ),
    ]
