# Generated by Django 5.2 on 2025-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pptx', 'PPTX'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], default='pptx', max_length=10),
        ),
    ]
